export const GET_TRANSACTIONS_REQUEST = 'GET_TRANSACTIONS_REQUEST'
export const GET_TRANSACTIONS_SUCCESS = 'GET_TRANSACTIONS_SUCCESS'
export const GET_TRANSACTIONS_FAILED = 'GET_TRANSACTIONS_FAILED'
export const GET_TRANSACTIONS_RESET = 'GET_TRANSACTIONS_RESET'


export const MAKE_DEBIT_TRANSACTIONS_REQUEST = 'MAKE_DEBIT_TRANSACTIONS_REQUEST'
export const MAKE_DEBIT_TRANSACTIONS_SUCCESS = 'MAKE_DEBIT_TRANSACTIONS_SUCCESS'
export const MAKE_DEBIT_TRANSACTIONS_FAILED = 'MAKE_DEBIT_TRANSACTIONS_FAILED'
export const MAKE_DEBIT_TRANSACTIONS_RESET = 'MAKE_DEBIT_TRANSACTIONS_RESET'