export const GET_USER_REQUEST = 'GET_USER_REQUEST'
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS'
export const GET_USER_FAILED = 'GET_USER_FAILED'
export const GET_USER_RESET = 'GET_USER_RESET'

export const GET_USER_ACCOUNTDETAILS_REQUEST = 'GET_USER_ACCOUNTDETAILS_REQUEST'
export const GET_USER_ACCOUNTDETAILS_SUCCESS = 'GET_USER_ACCOUNTDETAILS_SUCCESS'
export const GET_USER_ACCOUNTDETAILS_FAILED = 'GET_USER_ACCOUNTDETAILS_FAILED'
export const GET_USER_ACCOUNTDETAILS_RESET = 'GET_USER_ACCOUNTDETAILS_RESET'

export const GET_ALL_USERS_REQUEST = 'GET_ALL_USERS_REQUEST'
export const GET_ALL_USERS_SUCCESS = 'GET_ALL_USERS_SUCCESS'
export const GET_ALL_USERS_FAILED = 'GET_ALL_USERS_FAILED'
export const GET_ALL_USERS_RESET = 'GET_ALL_USERS_RESET'

export const CREATE_USER_REQUEST = 'CREATE_USER_REQUEST'
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS'
export const CREATE_USER_FAILED = 'CREATE_USER_FAILED'
export const CREATE_USER_RESET = 'CREATE_USER_RESET'

export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_FAILED = 'LOGIN_USER_FAILED'
export const LOGIN_USER_RESET = 'LOGIN_USER_RESET'

export const ISLOGGEDIN_REQUEST = 'ISLOGGEDIN_REQUEST'
export const ISLOGGEDIN_SUCCESS = 'ISLOGGEDIN_SUCCESS'
export const ISLOGGEDIN_FAILED = 'ISLOGGEDIN_FAILED'
export const ISLOGGEDIN_RESET = 'LOGIN_USER_RESET'

export const UPDATE_USERPASSWORD_REQUEST = 'UPDATE_USERPASSWORD_REQUEST'
export const UPDATE_USERPASSWORD_SUCCESS = 'UPDATE_USERPASSWORD_SUCCESS'
export const UPDATE_USERPASSWORD_FAILED = 'UPDATE_USERPASSWORD_FAILED'
export const UPDATE_USERPASSWORD_RESET = 'UPDATE_USERPASSWORD_RESET'

export const LOGOUT_USER = 'LOGOUT_USER'